/**
 * The theme's *names*, for tailwind-merge.
 *
 * `cn()` merges conflicting classes by asking tailwind-merge which group a class
 * belongs to. Out of the box it only knows Tailwind's own scale names, so with a
 * fully replaced theme it cannot tell `text-label` (a font size) from
 * `text-on-accent` (a colour) — it lumps them together and silently drops one.
 * That is not theoretical: it is what made a primary Button render slate body text
 * instead of `--text-on-accent`.
 *
 * This is the *only* place a design-system name is repeated, and no value is —
 * `tw-theme.test.ts` parses the `@theme inline` block in `styles.css` and fails if
 * these lists and that block ever disagree.
 */
export const twTheme = {
  color: [
    "transparent",
    "current",
    "inherit",
    "slate-950",
    "slate-900",
    "slate-800",
    "slate-700",
    "slate-600",
    "slate-500",
    "slate-400",
    "slate-300",
    "slate-200",
    "slate-100",
    "slate-50",
    "mist",
    "mist-deep",
    "frost",
    "verdigris-700",
    "verdigris-600",
    "verdigris-500",
    "verdigris-400",
    "verdigris-300",
    "verdigris-200",
    "verdigris-100",
    "crimson-700",
    "crimson-600",
    "crimson-500",
    "crimson-400",
    "crimson-200",
    "crimson-100",
    "emerald-700",
    "emerald-600",
    "emerald-500",
    "emerald-400",
    "emerald-200",
    "emerald-100",
    "violet-700",
    "violet-600",
    "violet-500",
    "violet-400",
    "violet-200",
    "violet-100",
    "azure-700",
    "azure-600",
    "azure-500",
    "azure-400",
    "azure-200",
    "azure-100",
    "background",
    "foreground",
    "card",
    "card-foreground",
    "popover",
    "popover-foreground",
    "primary",
    "primary-foreground",
    "secondary",
    "secondary-foreground",
    "muted",
    "muted-foreground",
    "accent",
    "accent-foreground",
    "destructive",
    "destructive-foreground",
    "border",
    "input",
    "ring",
    "surface-page",
    "surface-card",
    "surface-raised",
    "surface-sunken",
    "surface-inverse",
    "heading",
    "faint",
    "on-accent",
    "on-solid",
    "on-dark",
    "on-dark-muted",
    "link",
    "link-hover",
    "hairline",
    "strong",
    "accent-hover",
    "accent-press",
    "accent-soft",
    "accent-ink",
    "danger",
    "danger-hover",
    "danger-soft",
    "danger-ink",
    "success",
    "success-hover",
    "success-soft",
    "success-ink",
    "magic",
    "magic-hover",
    "magic-soft",
    "magic-ink",
    "info",
    "info-hover",
    "info-soft",
    "info-ink",
    "scrim",
  ],
  font: ["sans", "display", "serif", "mono"],
  text: [
    "micro",
    "label-s",
    "caption",
    "label",
    "mono",
    "label-l",
    "body-s",
    "mono-l",
    "body",
    "subtitle",
    "body-l",
    "title",
    "display-s",
    "display-m",
    "display-l",
    "display-xl",
  ],
  "font-weight": ["normal", "medium", "semibold", "bold", "black"],
  tracking: ["display", "tight", "normal", "wide", "caps"],
  leading: ["none", "tight", "snug", "heading", "body", "loose"],
  radius: [
    "xs",
    "sm",
    "md",
    "lg",
    "xl",
    "control",
    "card",
    "panel",
    "dialog",
    "tag",
    "pill",
    "circle",
  ],
  shadow: ["1", "2", "3", "dark", "inset-lip", "inset-press", "ring"],
  blur: ["scrim"],
  ease: ["out", "in-out", "settle"],
  animate: ["dialog-in", "dialog-out"],
  container: ["measure"],
} as const;

/**
 * Named layout measurements added *alongside* Tailwind's numeric spacing scale,
 * which the system keeps: every step of the 2px design scale already lands on it
 * (2px = `0.5`, 6px = `1.5`, 20px = `5`, …).
 */
export const twSpacing = [
  "control",
  "control-sm",
  "control-lg",
  "row",
  "card",
  "panel",
  "gutter",
  "page",
  "page-sm",
  "rail",
  "aside",
  "chat-panel",
] as const;
