/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonstersRouteImport } from './routes/monsters'
import { Route as IndexRouteImport } from './routes/index'

const MonstersRoute = MonstersRouteImport.update({
  id: '/monsters',
  path: '/monsters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/monsters': typeof MonstersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/monsters': typeof MonstersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/monsters': typeof MonstersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/monsters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/monsters'
  id: '__root__' | '/' | '/monsters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MonstersRoute: typeof MonstersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monsters': {
      id: '/monsters'
      path: '/monsters'
      fullPath: '/monsters'
      preLoaderRoute: typeof MonstersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MonstersRoute: MonstersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
