/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ShellRouteImport } from "./routes/_shell";
import { Route as StandaloneRouteImport } from "./routes/_standalone";
import { Route as ShellIndexRouteImport } from "./routes/_shell/index";
import { Route as ShellSplatRouteImport } from "./routes/_shell/$";
import { Route as ShellCampaignsIndexRouteImport } from "./routes/_shell/campaigns/index";
import { Route as ShellCampaignsCampaignIdRouteRouteImport } from "./routes/_shell/campaigns/$campaignId/route";
import { Route as ShellCharactersIndexRouteImport } from "./routes/_shell/characters/index";
import { Route as ShellCharactersSplatRouteImport } from "./routes/_shell/characters/$";
import { Route as ShellCharactersCharacterIdRouteImport } from "./routes/_shell/characters/$characterId";
import { Route as ShellCharactersNewRouteImport } from "./routes/_shell/characters/new";
import { Route as ShellLibraryIndexRouteImport } from "./routes/_shell/library/index";
import { Route as ShellLibraryCompendiumRouteImport } from "./routes/_shell/library/compendium";
import { Route as ShellLibraryEquipmentRouteImport } from "./routes/_shell/library/equipment";
import { Route as ShellLibraryMagicItemsRouteImport } from "./routes/_shell/library/magic-items";
import { Route as ShellLibraryRulesRouteImport } from "./routes/_shell/library/rules";
import { Route as ShellLibrarySpellsRouteImport } from "./routes/_shell/library/spells";
import { Route as ShellWorldsIndexRouteImport } from "./routes/_shell/worlds/index";
import { Route as ShellWorldsWorldIdRouteRouteImport } from "./routes/_shell/worlds/$worldId/route";
import { Route as StandaloneJoinTokenRouteImport } from "./routes/_standalone/join/$token";
import { Route as ShellCampaignsCampaignIdIndexRouteImport } from "./routes/_shell/campaigns/$campaignId/index";
import { Route as ShellCampaignsCampaignIdSplatRouteImport } from "./routes/_shell/campaigns/$campaignId/$";
import { Route as ShellCampaignsCampaignIdChronicleRouteImport } from "./routes/_shell/campaigns/$campaignId/chronicle";
import { Route as ShellCampaignsCampaignIdNotesRouteImport } from "./routes/_shell/campaigns/$campaignId/notes";
import { Route as ShellCampaignsCampaignIdTableRouteImport } from "./routes/_shell/campaigns/$campaignId/table";
import { Route as ShellLibraryNpcsIndexRouteImport } from "./routes/_shell/library/npcs/index";
import { Route as ShellLibraryNpcsSplatRouteImport } from "./routes/_shell/library/npcs/$";
import { Route as ShellLibraryNpcsNpcIdRouteImport } from "./routes/_shell/library/npcs/$npcId";
import { Route as ShellWorldsWorldIdIndexRouteImport } from "./routes/_shell/worlds/$worldId/index";
import { Route as ShellWorldsWorldIdChronicleRouteImport } from "./routes/_shell/worlds/$worldId/chronicle";
import { Route as ShellCampaignsCampaignIdCastIndexRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/index";
import { Route as ShellCampaignsCampaignIdCastSplatRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/$";
import { Route as ShellCampaignsCampaignIdCastNpcIdRouteRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/$npcId/route";
import { Route as ShellCampaignsCampaignIdCastArchivedRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/archived";
import { Route as ShellCampaignsCampaignIdCastFollowUpRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/follow-up";
import { Route as ShellCampaignsCampaignIdCharactersNewRouteImport } from "./routes/_shell/campaigns/$campaignId/characters/new";
import { Route as ShellCampaignsCampaignIdEncountersIndexRouteImport } from "./routes/_shell/campaigns/$campaignId/encounters/index";
import { Route as ShellCampaignsCampaignIdEncountersSplatRouteImport } from "./routes/_shell/campaigns/$campaignId/encounters/$";
import { Route as ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteImport } from "./routes/_shell/campaigns/$campaignId/encounters/$encounterId/route";
import { Route as ShellCampaignsCampaignIdEncountersNewRouteImport } from "./routes/_shell/campaigns/$campaignId/encounters/new";
import { Route as ShellCampaignsCampaignIdPartyIndexRouteImport } from "./routes/_shell/campaigns/$campaignId/party/index";
import { Route as ShellCampaignsCampaignIdPartySplatRouteImport } from "./routes/_shell/campaigns/$campaignId/party/$";
import { Route as ShellCampaignsCampaignIdPartySeatIdRouteImport } from "./routes/_shell/campaigns/$campaignId/party/$seatId";
import { Route as ShellCampaignsCampaignIdCastNpcIdIndexRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/$npcId/index";
import { Route as ShellCampaignsCampaignIdCastNpcIdTalkRouteImport } from "./routes/_shell/campaigns/$campaignId/cast/$npcId/talk";
import { Route as ShellCampaignsCampaignIdEncountersEncounterIdIndexRouteImport } from "./routes/_shell/campaigns/$campaignId/encounters/$encounterId/index";
import { Route as ShellCampaignsCampaignIdEncountersEncounterIdEditRouteImport } from "./routes/_shell/campaigns/$campaignId/encounters/$encounterId/edit";
import { Route as ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRouteImport } from "./routes/_shell/campaigns/$campaignId/sessions/$sessionId/runs/$runId";

const ShellRoute = ShellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => rootRouteImport,
} as any);
const StandaloneRoute = StandaloneRouteImport.update({
  id: "/_standalone",
  getParentRoute: () => rootRouteImport,
} as any);
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSplatRoute = ShellSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => ShellRoute,
} as any);
const ShellCampaignsIndexRoute = ShellCampaignsIndexRouteImport.update({
  id: "/campaigns/",
  path: "/campaigns/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellCampaignsCampaignIdRouteRoute =
  ShellCampaignsCampaignIdRouteRouteImport.update({
    id: "/campaigns/$campaignId",
    path: "/campaigns/$campaignId",
    getParentRoute: () => ShellRoute,
  } as any);
const ShellCharactersIndexRoute = ShellCharactersIndexRouteImport.update({
  id: "/characters/",
  path: "/characters/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellCharactersSplatRoute = ShellCharactersSplatRouteImport.update({
  id: "/characters/$",
  path: "/characters/$",
  getParentRoute: () => ShellRoute,
} as any);
const ShellCharactersCharacterIdRoute =
  ShellCharactersCharacterIdRouteImport.update({
    id: "/characters/$characterId",
    path: "/characters/$characterId",
    getParentRoute: () => ShellRoute,
  } as any);
const ShellCharactersNewRoute = ShellCharactersNewRouteImport.update({
  id: "/characters/new",
  path: "/characters/new",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryIndexRoute = ShellLibraryIndexRouteImport.update({
  id: "/library/",
  path: "/library/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryCompendiumRoute = ShellLibraryCompendiumRouteImport.update({
  id: "/library/compendium",
  path: "/library/compendium",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryEquipmentRoute = ShellLibraryEquipmentRouteImport.update({
  id: "/library/equipment",
  path: "/library/equipment",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryMagicItemsRoute = ShellLibraryMagicItemsRouteImport.update({
  id: "/library/magic-items",
  path: "/library/magic-items",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryRulesRoute = ShellLibraryRulesRouteImport.update({
  id: "/library/rules",
  path: "/library/rules",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibrarySpellsRoute = ShellLibrarySpellsRouteImport.update({
  id: "/library/spells",
  path: "/library/spells",
  getParentRoute: () => ShellRoute,
} as any);
const ShellWorldsIndexRoute = ShellWorldsIndexRouteImport.update({
  id: "/worlds/",
  path: "/worlds/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellWorldsWorldIdRouteRoute = ShellWorldsWorldIdRouteRouteImport.update({
  id: "/worlds/$worldId",
  path: "/worlds/$worldId",
  getParentRoute: () => ShellRoute,
} as any);
const StandaloneJoinTokenRoute = StandaloneJoinTokenRouteImport.update({
  id: "/join/$token",
  path: "/join/$token",
  getParentRoute: () => StandaloneRoute,
} as any);
const ShellCampaignsCampaignIdIndexRoute =
  ShellCampaignsCampaignIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdSplatRoute =
  ShellCampaignsCampaignIdSplatRouteImport.update({
    id: "/$",
    path: "/$",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdChronicleRoute =
  ShellCampaignsCampaignIdChronicleRouteImport.update({
    id: "/chronicle",
    path: "/chronicle",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdNotesRoute =
  ShellCampaignsCampaignIdNotesRouteImport.update({
    id: "/notes",
    path: "/notes",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdTableRoute =
  ShellCampaignsCampaignIdTableRouteImport.update({
    id: "/table",
    path: "/table",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellLibraryNpcsIndexRoute = ShellLibraryNpcsIndexRouteImport.update({
  id: "/library/npcs/",
  path: "/library/npcs/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryNpcsSplatRoute = ShellLibraryNpcsSplatRouteImport.update({
  id: "/library/npcs/$",
  path: "/library/npcs/$",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryNpcsNpcIdRoute = ShellLibraryNpcsNpcIdRouteImport.update({
  id: "/library/npcs/$npcId",
  path: "/library/npcs/$npcId",
  getParentRoute: () => ShellRoute,
} as any);
const ShellWorldsWorldIdIndexRoute = ShellWorldsWorldIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ShellWorldsWorldIdRouteRoute,
} as any);
const ShellWorldsWorldIdChronicleRoute =
  ShellWorldsWorldIdChronicleRouteImport.update({
    id: "/chronicle",
    path: "/chronicle",
    getParentRoute: () => ShellWorldsWorldIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastIndexRoute =
  ShellCampaignsCampaignIdCastIndexRouteImport.update({
    id: "/cast/",
    path: "/cast/",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastSplatRoute =
  ShellCampaignsCampaignIdCastSplatRouteImport.update({
    id: "/cast/$",
    path: "/cast/$",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastNpcIdRouteRoute =
  ShellCampaignsCampaignIdCastNpcIdRouteRouteImport.update({
    id: "/cast/$npcId",
    path: "/cast/$npcId",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastArchivedRoute =
  ShellCampaignsCampaignIdCastArchivedRouteImport.update({
    id: "/cast/archived",
    path: "/cast/archived",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastFollowUpRoute =
  ShellCampaignsCampaignIdCastFollowUpRouteImport.update({
    id: "/cast/follow-up",
    path: "/cast/follow-up",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCharactersNewRoute =
  ShellCampaignsCampaignIdCharactersNewRouteImport.update({
    id: "/characters/new",
    path: "/characters/new",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdEncountersIndexRoute =
  ShellCampaignsCampaignIdEncountersIndexRouteImport.update({
    id: "/encounters/",
    path: "/encounters/",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdEncountersSplatRoute =
  ShellCampaignsCampaignIdEncountersSplatRouteImport.update({
    id: "/encounters/$",
    path: "/encounters/$",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute =
  ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteImport.update({
    id: "/encounters/$encounterId",
    path: "/encounters/$encounterId",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdEncountersNewRoute =
  ShellCampaignsCampaignIdEncountersNewRouteImport.update({
    id: "/encounters/new",
    path: "/encounters/new",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdPartyIndexRoute =
  ShellCampaignsCampaignIdPartyIndexRouteImport.update({
    id: "/party/",
    path: "/party/",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdPartySplatRoute =
  ShellCampaignsCampaignIdPartySplatRouteImport.update({
    id: "/party/$",
    path: "/party/$",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdPartySeatIdRoute =
  ShellCampaignsCampaignIdPartySeatIdRouteImport.update({
    id: "/party/$seatId",
    path: "/party/$seatId",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastNpcIdIndexRoute =
  ShellCampaignsCampaignIdCastNpcIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => ShellCampaignsCampaignIdCastNpcIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdCastNpcIdTalkRoute =
  ShellCampaignsCampaignIdCastNpcIdTalkRouteImport.update({
    id: "/talk",
    path: "/talk",
    getParentRoute: () => ShellCampaignsCampaignIdCastNpcIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute =
  ShellCampaignsCampaignIdEncountersEncounterIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () =>
      ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdEncountersEncounterIdEditRoute =
  ShellCampaignsCampaignIdEncountersEncounterIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () =>
      ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute,
  } as any);
const ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute =
  ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRouteImport.update({
    id: "/sessions/$sessionId/runs/$runId",
    path: "/sessions/$sessionId/runs/$runId",
    getParentRoute: () => ShellCampaignsCampaignIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof ShellIndexRoute;
  "/$": typeof ShellSplatRoute;
  "/campaigns/$campaignId": typeof ShellCampaignsCampaignIdRouteRouteWithChildren;
  "/worlds/$worldId": typeof ShellWorldsWorldIdRouteRouteWithChildren;
  "/characters/$": typeof ShellCharactersSplatRoute;
  "/characters/$characterId": typeof ShellCharactersCharacterIdRoute;
  "/characters/new": typeof ShellCharactersNewRoute;
  "/library/compendium": typeof ShellLibraryCompendiumRoute;
  "/library/equipment": typeof ShellLibraryEquipmentRoute;
  "/library/magic-items": typeof ShellLibraryMagicItemsRoute;
  "/library/rules": typeof ShellLibraryRulesRoute;
  "/library/spells": typeof ShellLibrarySpellsRoute;
  "/join/$token": typeof StandaloneJoinTokenRoute;
  "/campaigns/": typeof ShellCampaignsIndexRoute;
  "/characters/": typeof ShellCharactersIndexRoute;
  "/library/": typeof ShellLibraryIndexRoute;
  "/worlds/": typeof ShellWorldsIndexRoute;
  "/campaigns/$campaignId/$": typeof ShellCampaignsCampaignIdSplatRoute;
  "/campaigns/$campaignId/chronicle": typeof ShellCampaignsCampaignIdChronicleRoute;
  "/campaigns/$campaignId/notes": typeof ShellCampaignsCampaignIdNotesRoute;
  "/campaigns/$campaignId/table": typeof ShellCampaignsCampaignIdTableRoute;
  "/library/npcs/$": typeof ShellLibraryNpcsSplatRoute;
  "/library/npcs/$npcId": typeof ShellLibraryNpcsNpcIdRoute;
  "/worlds/$worldId/chronicle": typeof ShellWorldsWorldIdChronicleRoute;
  "/campaigns/$campaignId/": typeof ShellCampaignsCampaignIdIndexRoute;
  "/library/npcs/": typeof ShellLibraryNpcsIndexRoute;
  "/worlds/$worldId/": typeof ShellWorldsWorldIdIndexRoute;
  "/campaigns/$campaignId/cast/$npcId": typeof ShellCampaignsCampaignIdCastNpcIdRouteRouteWithChildren;
  "/campaigns/$campaignId/encounters/$encounterId": typeof ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteWithChildren;
  "/campaigns/$campaignId/cast/$": typeof ShellCampaignsCampaignIdCastSplatRoute;
  "/campaigns/$campaignId/cast/archived": typeof ShellCampaignsCampaignIdCastArchivedRoute;
  "/campaigns/$campaignId/cast/follow-up": typeof ShellCampaignsCampaignIdCastFollowUpRoute;
  "/campaigns/$campaignId/characters/new": typeof ShellCampaignsCampaignIdCharactersNewRoute;
  "/campaigns/$campaignId/encounters/$": typeof ShellCampaignsCampaignIdEncountersSplatRoute;
  "/campaigns/$campaignId/encounters/new": typeof ShellCampaignsCampaignIdEncountersNewRoute;
  "/campaigns/$campaignId/party/$": typeof ShellCampaignsCampaignIdPartySplatRoute;
  "/campaigns/$campaignId/party/$seatId": typeof ShellCampaignsCampaignIdPartySeatIdRoute;
  "/campaigns/$campaignId/cast/": typeof ShellCampaignsCampaignIdCastIndexRoute;
  "/campaigns/$campaignId/encounters/": typeof ShellCampaignsCampaignIdEncountersIndexRoute;
  "/campaigns/$campaignId/party/": typeof ShellCampaignsCampaignIdPartyIndexRoute;
  "/campaigns/$campaignId/cast/$npcId/talk": typeof ShellCampaignsCampaignIdCastNpcIdTalkRoute;
  "/campaigns/$campaignId/encounters/$encounterId/edit": typeof ShellCampaignsCampaignIdEncountersEncounterIdEditRoute;
  "/campaigns/$campaignId/cast/$npcId/": typeof ShellCampaignsCampaignIdCastNpcIdIndexRoute;
  "/campaigns/$campaignId/encounters/$encounterId/": typeof ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute;
  "/campaigns/$campaignId/sessions/$sessionId/runs/$runId": typeof ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof ShellIndexRoute;
  "/$": typeof ShellSplatRoute;
  "/characters/$": typeof ShellCharactersSplatRoute;
  "/characters/$characterId": typeof ShellCharactersCharacterIdRoute;
  "/characters/new": typeof ShellCharactersNewRoute;
  "/library/compendium": typeof ShellLibraryCompendiumRoute;
  "/library/equipment": typeof ShellLibraryEquipmentRoute;
  "/library/magic-items": typeof ShellLibraryMagicItemsRoute;
  "/library/rules": typeof ShellLibraryRulesRoute;
  "/library/spells": typeof ShellLibrarySpellsRoute;
  "/join/$token": typeof StandaloneJoinTokenRoute;
  "/campaigns": typeof ShellCampaignsIndexRoute;
  "/characters": typeof ShellCharactersIndexRoute;
  "/library": typeof ShellLibraryIndexRoute;
  "/worlds": typeof ShellWorldsIndexRoute;
  "/campaigns/$campaignId/$": typeof ShellCampaignsCampaignIdSplatRoute;
  "/campaigns/$campaignId/chronicle": typeof ShellCampaignsCampaignIdChronicleRoute;
  "/campaigns/$campaignId/notes": typeof ShellCampaignsCampaignIdNotesRoute;
  "/campaigns/$campaignId/table": typeof ShellCampaignsCampaignIdTableRoute;
  "/library/npcs/$": typeof ShellLibraryNpcsSplatRoute;
  "/library/npcs/$npcId": typeof ShellLibraryNpcsNpcIdRoute;
  "/worlds/$worldId/chronicle": typeof ShellWorldsWorldIdChronicleRoute;
  "/campaigns/$campaignId": typeof ShellCampaignsCampaignIdIndexRoute;
  "/library/npcs": typeof ShellLibraryNpcsIndexRoute;
  "/worlds/$worldId": typeof ShellWorldsWorldIdIndexRoute;
  "/campaigns/$campaignId/cast/$": typeof ShellCampaignsCampaignIdCastSplatRoute;
  "/campaigns/$campaignId/cast/archived": typeof ShellCampaignsCampaignIdCastArchivedRoute;
  "/campaigns/$campaignId/cast/follow-up": typeof ShellCampaignsCampaignIdCastFollowUpRoute;
  "/campaigns/$campaignId/characters/new": typeof ShellCampaignsCampaignIdCharactersNewRoute;
  "/campaigns/$campaignId/encounters/$": typeof ShellCampaignsCampaignIdEncountersSplatRoute;
  "/campaigns/$campaignId/encounters/new": typeof ShellCampaignsCampaignIdEncountersNewRoute;
  "/campaigns/$campaignId/party/$": typeof ShellCampaignsCampaignIdPartySplatRoute;
  "/campaigns/$campaignId/party/$seatId": typeof ShellCampaignsCampaignIdPartySeatIdRoute;
  "/campaigns/$campaignId/cast": typeof ShellCampaignsCampaignIdCastIndexRoute;
  "/campaigns/$campaignId/encounters": typeof ShellCampaignsCampaignIdEncountersIndexRoute;
  "/campaigns/$campaignId/party": typeof ShellCampaignsCampaignIdPartyIndexRoute;
  "/campaigns/$campaignId/cast/$npcId/talk": typeof ShellCampaignsCampaignIdCastNpcIdTalkRoute;
  "/campaigns/$campaignId/encounters/$encounterId/edit": typeof ShellCampaignsCampaignIdEncountersEncounterIdEditRoute;
  "/campaigns/$campaignId/cast/$npcId": typeof ShellCampaignsCampaignIdCastNpcIdIndexRoute;
  "/campaigns/$campaignId/encounters/$encounterId": typeof ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute;
  "/campaigns/$campaignId/sessions/$sessionId/runs/$runId": typeof ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_shell": typeof ShellRouteWithChildren;
  "/_standalone": typeof StandaloneRouteWithChildren;
  "/_shell/$": typeof ShellSplatRoute;
  "/_shell/": typeof ShellIndexRoute;
  "/_shell/campaigns/$campaignId": typeof ShellCampaignsCampaignIdRouteRouteWithChildren;
  "/_shell/worlds/$worldId": typeof ShellWorldsWorldIdRouteRouteWithChildren;
  "/_shell/characters/$": typeof ShellCharactersSplatRoute;
  "/_shell/characters/$characterId": typeof ShellCharactersCharacterIdRoute;
  "/_shell/characters/new": typeof ShellCharactersNewRoute;
  "/_shell/library/compendium": typeof ShellLibraryCompendiumRoute;
  "/_shell/library/equipment": typeof ShellLibraryEquipmentRoute;
  "/_shell/library/magic-items": typeof ShellLibraryMagicItemsRoute;
  "/_shell/library/rules": typeof ShellLibraryRulesRoute;
  "/_shell/library/spells": typeof ShellLibrarySpellsRoute;
  "/_standalone/join/$token": typeof StandaloneJoinTokenRoute;
  "/_shell/campaigns/": typeof ShellCampaignsIndexRoute;
  "/_shell/characters/": typeof ShellCharactersIndexRoute;
  "/_shell/library/": typeof ShellLibraryIndexRoute;
  "/_shell/worlds/": typeof ShellWorldsIndexRoute;
  "/_shell/campaigns/$campaignId/$": typeof ShellCampaignsCampaignIdSplatRoute;
  "/_shell/campaigns/$campaignId/chronicle": typeof ShellCampaignsCampaignIdChronicleRoute;
  "/_shell/campaigns/$campaignId/notes": typeof ShellCampaignsCampaignIdNotesRoute;
  "/_shell/campaigns/$campaignId/table": typeof ShellCampaignsCampaignIdTableRoute;
  "/_shell/library/npcs/$": typeof ShellLibraryNpcsSplatRoute;
  "/_shell/library/npcs/$npcId": typeof ShellLibraryNpcsNpcIdRoute;
  "/_shell/worlds/$worldId/chronicle": typeof ShellWorldsWorldIdChronicleRoute;
  "/_shell/campaigns/$campaignId/": typeof ShellCampaignsCampaignIdIndexRoute;
  "/_shell/library/npcs/": typeof ShellLibraryNpcsIndexRoute;
  "/_shell/worlds/$worldId/": typeof ShellWorldsWorldIdIndexRoute;
  "/_shell/campaigns/$campaignId/cast/$npcId": typeof ShellCampaignsCampaignIdCastNpcIdRouteRouteWithChildren;
  "/_shell/campaigns/$campaignId/encounters/$encounterId": typeof ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteWithChildren;
  "/_shell/campaigns/$campaignId/cast/$": typeof ShellCampaignsCampaignIdCastSplatRoute;
  "/_shell/campaigns/$campaignId/cast/archived": typeof ShellCampaignsCampaignIdCastArchivedRoute;
  "/_shell/campaigns/$campaignId/cast/follow-up": typeof ShellCampaignsCampaignIdCastFollowUpRoute;
  "/_shell/campaigns/$campaignId/characters/new": typeof ShellCampaignsCampaignIdCharactersNewRoute;
  "/_shell/campaigns/$campaignId/encounters/$": typeof ShellCampaignsCampaignIdEncountersSplatRoute;
  "/_shell/campaigns/$campaignId/encounters/new": typeof ShellCampaignsCampaignIdEncountersNewRoute;
  "/_shell/campaigns/$campaignId/party/$": typeof ShellCampaignsCampaignIdPartySplatRoute;
  "/_shell/campaigns/$campaignId/party/$seatId": typeof ShellCampaignsCampaignIdPartySeatIdRoute;
  "/_shell/campaigns/$campaignId/cast/": typeof ShellCampaignsCampaignIdCastIndexRoute;
  "/_shell/campaigns/$campaignId/encounters/": typeof ShellCampaignsCampaignIdEncountersIndexRoute;
  "/_shell/campaigns/$campaignId/party/": typeof ShellCampaignsCampaignIdPartyIndexRoute;
  "/_shell/campaigns/$campaignId/cast/$npcId/talk": typeof ShellCampaignsCampaignIdCastNpcIdTalkRoute;
  "/_shell/campaigns/$campaignId/encounters/$encounterId/edit": typeof ShellCampaignsCampaignIdEncountersEncounterIdEditRoute;
  "/_shell/campaigns/$campaignId/cast/$npcId/": typeof ShellCampaignsCampaignIdCastNpcIdIndexRoute;
  "/_shell/campaigns/$campaignId/encounters/$encounterId/": typeof ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute;
  "/_shell/campaigns/$campaignId/sessions/$sessionId/runs/$runId": typeof ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/campaigns/$campaignId"
    | "/worlds/$worldId"
    | "/characters/$"
    | "/characters/$characterId"
    | "/characters/new"
    | "/library/compendium"
    | "/library/equipment"
    | "/library/magic-items"
    | "/library/rules"
    | "/library/spells"
    | "/join/$token"
    | "/campaigns/"
    | "/characters/"
    | "/library/"
    | "/worlds/"
    | "/campaigns/$campaignId/$"
    | "/campaigns/$campaignId/chronicle"
    | "/campaigns/$campaignId/notes"
    | "/campaigns/$campaignId/table"
    | "/library/npcs/$"
    | "/library/npcs/$npcId"
    | "/worlds/$worldId/chronicle"
    | "/campaigns/$campaignId/"
    | "/library/npcs/"
    | "/worlds/$worldId/"
    | "/campaigns/$campaignId/cast/$npcId"
    | "/campaigns/$campaignId/encounters/$encounterId"
    | "/campaigns/$campaignId/cast/$"
    | "/campaigns/$campaignId/cast/archived"
    | "/campaigns/$campaignId/cast/follow-up"
    | "/campaigns/$campaignId/characters/new"
    | "/campaigns/$campaignId/encounters/$"
    | "/campaigns/$campaignId/encounters/new"
    | "/campaigns/$campaignId/party/$"
    | "/campaigns/$campaignId/party/$seatId"
    | "/campaigns/$campaignId/cast/"
    | "/campaigns/$campaignId/encounters/"
    | "/campaigns/$campaignId/party/"
    | "/campaigns/$campaignId/cast/$npcId/talk"
    | "/campaigns/$campaignId/encounters/$encounterId/edit"
    | "/campaigns/$campaignId/cast/$npcId/"
    | "/campaigns/$campaignId/encounters/$encounterId/"
    | "/campaigns/$campaignId/sessions/$sessionId/runs/$runId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/characters/$"
    | "/characters/$characterId"
    | "/characters/new"
    | "/library/compendium"
    | "/library/equipment"
    | "/library/magic-items"
    | "/library/rules"
    | "/library/spells"
    | "/join/$token"
    | "/campaigns"
    | "/characters"
    | "/library"
    | "/worlds"
    | "/campaigns/$campaignId/$"
    | "/campaigns/$campaignId/chronicle"
    | "/campaigns/$campaignId/notes"
    | "/campaigns/$campaignId/table"
    | "/library/npcs/$"
    | "/library/npcs/$npcId"
    | "/worlds/$worldId/chronicle"
    | "/campaigns/$campaignId"
    | "/library/npcs"
    | "/worlds/$worldId"
    | "/campaigns/$campaignId/cast/$"
    | "/campaigns/$campaignId/cast/archived"
    | "/campaigns/$campaignId/cast/follow-up"
    | "/campaigns/$campaignId/characters/new"
    | "/campaigns/$campaignId/encounters/$"
    | "/campaigns/$campaignId/encounters/new"
    | "/campaigns/$campaignId/party/$"
    | "/campaigns/$campaignId/party/$seatId"
    | "/campaigns/$campaignId/cast"
    | "/campaigns/$campaignId/encounters"
    | "/campaigns/$campaignId/party"
    | "/campaigns/$campaignId/cast/$npcId/talk"
    | "/campaigns/$campaignId/encounters/$encounterId/edit"
    | "/campaigns/$campaignId/cast/$npcId"
    | "/campaigns/$campaignId/encounters/$encounterId"
    | "/campaigns/$campaignId/sessions/$sessionId/runs/$runId";
  id:
    | "__root__"
    | "/_shell"
    | "/_standalone"
    | "/_shell/$"
    | "/_shell/"
    | "/_shell/campaigns/$campaignId"
    | "/_shell/worlds/$worldId"
    | "/_shell/characters/$"
    | "/_shell/characters/$characterId"
    | "/_shell/characters/new"
    | "/_shell/library/compendium"
    | "/_shell/library/equipment"
    | "/_shell/library/magic-items"
    | "/_shell/library/rules"
    | "/_shell/library/spells"
    | "/_standalone/join/$token"
    | "/_shell/campaigns/"
    | "/_shell/characters/"
    | "/_shell/library/"
    | "/_shell/worlds/"
    | "/_shell/campaigns/$campaignId/$"
    | "/_shell/campaigns/$campaignId/chronicle"
    | "/_shell/campaigns/$campaignId/notes"
    | "/_shell/campaigns/$campaignId/table"
    | "/_shell/library/npcs/$"
    | "/_shell/library/npcs/$npcId"
    | "/_shell/worlds/$worldId/chronicle"
    | "/_shell/campaigns/$campaignId/"
    | "/_shell/library/npcs/"
    | "/_shell/worlds/$worldId/"
    | "/_shell/campaigns/$campaignId/cast/$npcId"
    | "/_shell/campaigns/$campaignId/encounters/$encounterId"
    | "/_shell/campaigns/$campaignId/cast/$"
    | "/_shell/campaigns/$campaignId/cast/archived"
    | "/_shell/campaigns/$campaignId/cast/follow-up"
    | "/_shell/campaigns/$campaignId/characters/new"
    | "/_shell/campaigns/$campaignId/encounters/$"
    | "/_shell/campaigns/$campaignId/encounters/new"
    | "/_shell/campaigns/$campaignId/party/$"
    | "/_shell/campaigns/$campaignId/party/$seatId"
    | "/_shell/campaigns/$campaignId/cast/"
    | "/_shell/campaigns/$campaignId/encounters/"
    | "/_shell/campaigns/$campaignId/party/"
    | "/_shell/campaigns/$campaignId/cast/$npcId/talk"
    | "/_shell/campaigns/$campaignId/encounters/$encounterId/edit"
    | "/_shell/campaigns/$campaignId/cast/$npcId/"
    | "/_shell/campaigns/$campaignId/encounters/$encounterId/"
    | "/_shell/campaigns/$campaignId/sessions/$sessionId/runs/$runId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren;
  StandaloneRoute: typeof StandaloneRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_shell": {
      id: "/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ShellRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_standalone": {
      id: "/_standalone";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof StandaloneRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell/": {
      id: "/_shell/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ShellIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/$": {
      id: "/_shell/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof ShellSplatRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/campaigns/": {
      id: "/_shell/campaigns/";
      path: "/campaigns";
      fullPath: "/campaigns/";
      preLoaderRoute: typeof ShellCampaignsIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/campaigns/$campaignId": {
      id: "/_shell/campaigns/$campaignId";
      path: "/campaigns/$campaignId";
      fullPath: "/campaigns/$campaignId";
      preLoaderRoute: typeof ShellCampaignsCampaignIdRouteRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/characters/": {
      id: "/_shell/characters/";
      path: "/characters";
      fullPath: "/characters/";
      preLoaderRoute: typeof ShellCharactersIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/characters/$": {
      id: "/_shell/characters/$";
      path: "/characters/$";
      fullPath: "/characters/$";
      preLoaderRoute: typeof ShellCharactersSplatRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/characters/$characterId": {
      id: "/_shell/characters/$characterId";
      path: "/characters/$characterId";
      fullPath: "/characters/$characterId";
      preLoaderRoute: typeof ShellCharactersCharacterIdRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/characters/new": {
      id: "/_shell/characters/new";
      path: "/characters/new";
      fullPath: "/characters/new";
      preLoaderRoute: typeof ShellCharactersNewRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/": {
      id: "/_shell/library/";
      path: "/library";
      fullPath: "/library/";
      preLoaderRoute: typeof ShellLibraryIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/compendium": {
      id: "/_shell/library/compendium";
      path: "/library/compendium";
      fullPath: "/library/compendium";
      preLoaderRoute: typeof ShellLibraryCompendiumRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/equipment": {
      id: "/_shell/library/equipment";
      path: "/library/equipment";
      fullPath: "/library/equipment";
      preLoaderRoute: typeof ShellLibraryEquipmentRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/magic-items": {
      id: "/_shell/library/magic-items";
      path: "/library/magic-items";
      fullPath: "/library/magic-items";
      preLoaderRoute: typeof ShellLibraryMagicItemsRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/rules": {
      id: "/_shell/library/rules";
      path: "/library/rules";
      fullPath: "/library/rules";
      preLoaderRoute: typeof ShellLibraryRulesRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/spells": {
      id: "/_shell/library/spells";
      path: "/library/spells";
      fullPath: "/library/spells";
      preLoaderRoute: typeof ShellLibrarySpellsRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/worlds/": {
      id: "/_shell/worlds/";
      path: "/worlds";
      fullPath: "/worlds/";
      preLoaderRoute: typeof ShellWorldsIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/worlds/$worldId": {
      id: "/_shell/worlds/$worldId";
      path: "/worlds/$worldId";
      fullPath: "/worlds/$worldId";
      preLoaderRoute: typeof ShellWorldsWorldIdRouteRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_standalone/join/$token": {
      id: "/_standalone/join/$token";
      path: "/join/$token";
      fullPath: "/join/$token";
      preLoaderRoute: typeof StandaloneJoinTokenRouteImport;
      parentRoute: typeof StandaloneRoute;
    };
    "/_shell/campaigns/$campaignId/": {
      id: "/_shell/campaigns/$campaignId/";
      path: "/";
      fullPath: "/campaigns/$campaignId/";
      preLoaderRoute: typeof ShellCampaignsCampaignIdIndexRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/$": {
      id: "/_shell/campaigns/$campaignId/$";
      path: "/$";
      fullPath: "/campaigns/$campaignId/$";
      preLoaderRoute: typeof ShellCampaignsCampaignIdSplatRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/chronicle": {
      id: "/_shell/campaigns/$campaignId/chronicle";
      path: "/chronicle";
      fullPath: "/campaigns/$campaignId/chronicle";
      preLoaderRoute: typeof ShellCampaignsCampaignIdChronicleRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/notes": {
      id: "/_shell/campaigns/$campaignId/notes";
      path: "/notes";
      fullPath: "/campaigns/$campaignId/notes";
      preLoaderRoute: typeof ShellCampaignsCampaignIdNotesRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/table": {
      id: "/_shell/campaigns/$campaignId/table";
      path: "/table";
      fullPath: "/campaigns/$campaignId/table";
      preLoaderRoute: typeof ShellCampaignsCampaignIdTableRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/library/npcs/": {
      id: "/_shell/library/npcs/";
      path: "/library/npcs";
      fullPath: "/library/npcs/";
      preLoaderRoute: typeof ShellLibraryNpcsIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/npcs/$": {
      id: "/_shell/library/npcs/$";
      path: "/library/npcs/$";
      fullPath: "/library/npcs/$";
      preLoaderRoute: typeof ShellLibraryNpcsSplatRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/library/npcs/$npcId": {
      id: "/_shell/library/npcs/$npcId";
      path: "/library/npcs/$npcId";
      fullPath: "/library/npcs/$npcId";
      preLoaderRoute: typeof ShellLibraryNpcsNpcIdRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/worlds/$worldId/": {
      id: "/_shell/worlds/$worldId/";
      path: "/";
      fullPath: "/worlds/$worldId/";
      preLoaderRoute: typeof ShellWorldsWorldIdIndexRouteImport;
      parentRoute: typeof ShellWorldsWorldIdRouteRoute;
    };
    "/_shell/worlds/$worldId/chronicle": {
      id: "/_shell/worlds/$worldId/chronicle";
      path: "/chronicle";
      fullPath: "/worlds/$worldId/chronicle";
      preLoaderRoute: typeof ShellWorldsWorldIdChronicleRouteImport;
      parentRoute: typeof ShellWorldsWorldIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/": {
      id: "/_shell/campaigns/$campaignId/cast/";
      path: "/cast";
      fullPath: "/campaigns/$campaignId/cast/";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastIndexRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/$": {
      id: "/_shell/campaigns/$campaignId/cast/$";
      path: "/cast/$";
      fullPath: "/campaigns/$campaignId/cast/$";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastSplatRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/$npcId": {
      id: "/_shell/campaigns/$campaignId/cast/$npcId";
      path: "/cast/$npcId";
      fullPath: "/campaigns/$campaignId/cast/$npcId";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastNpcIdRouteRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/archived": {
      id: "/_shell/campaigns/$campaignId/cast/archived";
      path: "/cast/archived";
      fullPath: "/campaigns/$campaignId/cast/archived";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastArchivedRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/follow-up": {
      id: "/_shell/campaigns/$campaignId/cast/follow-up";
      path: "/cast/follow-up";
      fullPath: "/campaigns/$campaignId/cast/follow-up";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastFollowUpRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/characters/new": {
      id: "/_shell/campaigns/$campaignId/characters/new";
      path: "/characters/new";
      fullPath: "/campaigns/$campaignId/characters/new";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCharactersNewRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/encounters/": {
      id: "/_shell/campaigns/$campaignId/encounters/";
      path: "/encounters";
      fullPath: "/campaigns/$campaignId/encounters/";
      preLoaderRoute: typeof ShellCampaignsCampaignIdEncountersIndexRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/encounters/$": {
      id: "/_shell/campaigns/$campaignId/encounters/$";
      path: "/encounters/$";
      fullPath: "/campaigns/$campaignId/encounters/$";
      preLoaderRoute: typeof ShellCampaignsCampaignIdEncountersSplatRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/encounters/$encounterId": {
      id: "/_shell/campaigns/$campaignId/encounters/$encounterId";
      path: "/encounters/$encounterId";
      fullPath: "/campaigns/$campaignId/encounters/$encounterId";
      preLoaderRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/encounters/new": {
      id: "/_shell/campaigns/$campaignId/encounters/new";
      path: "/encounters/new";
      fullPath: "/campaigns/$campaignId/encounters/new";
      preLoaderRoute: typeof ShellCampaignsCampaignIdEncountersNewRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/party/": {
      id: "/_shell/campaigns/$campaignId/party/";
      path: "/party";
      fullPath: "/campaigns/$campaignId/party/";
      preLoaderRoute: typeof ShellCampaignsCampaignIdPartyIndexRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/party/$": {
      id: "/_shell/campaigns/$campaignId/party/$";
      path: "/party/$";
      fullPath: "/campaigns/$campaignId/party/$";
      preLoaderRoute: typeof ShellCampaignsCampaignIdPartySplatRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/party/$seatId": {
      id: "/_shell/campaigns/$campaignId/party/$seatId";
      path: "/party/$seatId";
      fullPath: "/campaigns/$campaignId/party/$seatId";
      preLoaderRoute: typeof ShellCampaignsCampaignIdPartySeatIdRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/$npcId/": {
      id: "/_shell/campaigns/$campaignId/cast/$npcId/";
      path: "/";
      fullPath: "/campaigns/$campaignId/cast/$npcId/";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastNpcIdIndexRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdCastNpcIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/cast/$npcId/talk": {
      id: "/_shell/campaigns/$campaignId/cast/$npcId/talk";
      path: "/talk";
      fullPath: "/campaigns/$campaignId/cast/$npcId/talk";
      preLoaderRoute: typeof ShellCampaignsCampaignIdCastNpcIdTalkRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdCastNpcIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/encounters/$encounterId/": {
      id: "/_shell/campaigns/$campaignId/encounters/$encounterId/";
      path: "/";
      fullPath: "/campaigns/$campaignId/encounters/$encounterId/";
      preLoaderRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdIndexRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/encounters/$encounterId/edit": {
      id: "/_shell/campaigns/$campaignId/encounters/$encounterId/edit";
      path: "/edit";
      fullPath: "/campaigns/$campaignId/encounters/$encounterId/edit";
      preLoaderRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdEditRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute;
    };
    "/_shell/campaigns/$campaignId/sessions/$sessionId/runs/$runId": {
      id: "/_shell/campaigns/$campaignId/sessions/$sessionId/runs/$runId";
      path: "/sessions/$sessionId/runs/$runId";
      fullPath: "/campaigns/$campaignId/sessions/$sessionId/runs/$runId";
      preLoaderRoute: typeof ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRouteImport;
      parentRoute: typeof ShellCampaignsCampaignIdRouteRoute;
    };
  }
}

interface ShellCampaignsCampaignIdCastNpcIdRouteRouteChildren {
  ShellCampaignsCampaignIdCastNpcIdTalkRoute: typeof ShellCampaignsCampaignIdCastNpcIdTalkRoute;
  ShellCampaignsCampaignIdCastNpcIdIndexRoute: typeof ShellCampaignsCampaignIdCastNpcIdIndexRoute;
}

const ShellCampaignsCampaignIdCastNpcIdRouteRouteChildren: ShellCampaignsCampaignIdCastNpcIdRouteRouteChildren =
  {
    ShellCampaignsCampaignIdCastNpcIdTalkRoute:
      ShellCampaignsCampaignIdCastNpcIdTalkRoute,
    ShellCampaignsCampaignIdCastNpcIdIndexRoute:
      ShellCampaignsCampaignIdCastNpcIdIndexRoute,
  };

const ShellCampaignsCampaignIdCastNpcIdRouteRouteWithChildren =
  ShellCampaignsCampaignIdCastNpcIdRouteRoute._addFileChildren(
    ShellCampaignsCampaignIdCastNpcIdRouteRouteChildren,
  );

interface ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteChildren {
  ShellCampaignsCampaignIdEncountersEncounterIdEditRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdEditRoute;
  ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute;
}

const ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteChildren: ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteChildren =
  {
    ShellCampaignsCampaignIdEncountersEncounterIdEditRoute:
      ShellCampaignsCampaignIdEncountersEncounterIdEditRoute,
    ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute:
      ShellCampaignsCampaignIdEncountersEncounterIdIndexRoute,
  };

const ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteWithChildren =
  ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute._addFileChildren(
    ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteChildren,
  );

interface ShellCampaignsCampaignIdRouteRouteChildren {
  ShellCampaignsCampaignIdSplatRoute: typeof ShellCampaignsCampaignIdSplatRoute;
  ShellCampaignsCampaignIdChronicleRoute: typeof ShellCampaignsCampaignIdChronicleRoute;
  ShellCampaignsCampaignIdNotesRoute: typeof ShellCampaignsCampaignIdNotesRoute;
  ShellCampaignsCampaignIdTableRoute: typeof ShellCampaignsCampaignIdTableRoute;
  ShellCampaignsCampaignIdIndexRoute: typeof ShellCampaignsCampaignIdIndexRoute;
  ShellCampaignsCampaignIdCastNpcIdRouteRoute: typeof ShellCampaignsCampaignIdCastNpcIdRouteRouteWithChildren;
  ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute: typeof ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteWithChildren;
  ShellCampaignsCampaignIdCastSplatRoute: typeof ShellCampaignsCampaignIdCastSplatRoute;
  ShellCampaignsCampaignIdCastArchivedRoute: typeof ShellCampaignsCampaignIdCastArchivedRoute;
  ShellCampaignsCampaignIdCastFollowUpRoute: typeof ShellCampaignsCampaignIdCastFollowUpRoute;
  ShellCampaignsCampaignIdCharactersNewRoute: typeof ShellCampaignsCampaignIdCharactersNewRoute;
  ShellCampaignsCampaignIdEncountersSplatRoute: typeof ShellCampaignsCampaignIdEncountersSplatRoute;
  ShellCampaignsCampaignIdEncountersNewRoute: typeof ShellCampaignsCampaignIdEncountersNewRoute;
  ShellCampaignsCampaignIdPartySplatRoute: typeof ShellCampaignsCampaignIdPartySplatRoute;
  ShellCampaignsCampaignIdPartySeatIdRoute: typeof ShellCampaignsCampaignIdPartySeatIdRoute;
  ShellCampaignsCampaignIdCastIndexRoute: typeof ShellCampaignsCampaignIdCastIndexRoute;
  ShellCampaignsCampaignIdEncountersIndexRoute: typeof ShellCampaignsCampaignIdEncountersIndexRoute;
  ShellCampaignsCampaignIdPartyIndexRoute: typeof ShellCampaignsCampaignIdPartyIndexRoute;
  ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute: typeof ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute;
}

const ShellCampaignsCampaignIdRouteRouteChildren: ShellCampaignsCampaignIdRouteRouteChildren =
  {
    ShellCampaignsCampaignIdSplatRoute: ShellCampaignsCampaignIdSplatRoute,
    ShellCampaignsCampaignIdChronicleRoute:
      ShellCampaignsCampaignIdChronicleRoute,
    ShellCampaignsCampaignIdNotesRoute: ShellCampaignsCampaignIdNotesRoute,
    ShellCampaignsCampaignIdTableRoute: ShellCampaignsCampaignIdTableRoute,
    ShellCampaignsCampaignIdIndexRoute: ShellCampaignsCampaignIdIndexRoute,
    ShellCampaignsCampaignIdCastNpcIdRouteRoute:
      ShellCampaignsCampaignIdCastNpcIdRouteRouteWithChildren,
    ShellCampaignsCampaignIdEncountersEncounterIdRouteRoute:
      ShellCampaignsCampaignIdEncountersEncounterIdRouteRouteWithChildren,
    ShellCampaignsCampaignIdCastSplatRoute:
      ShellCampaignsCampaignIdCastSplatRoute,
    ShellCampaignsCampaignIdCastArchivedRoute:
      ShellCampaignsCampaignIdCastArchivedRoute,
    ShellCampaignsCampaignIdCastFollowUpRoute:
      ShellCampaignsCampaignIdCastFollowUpRoute,
    ShellCampaignsCampaignIdCharactersNewRoute:
      ShellCampaignsCampaignIdCharactersNewRoute,
    ShellCampaignsCampaignIdEncountersSplatRoute:
      ShellCampaignsCampaignIdEncountersSplatRoute,
    ShellCampaignsCampaignIdEncountersNewRoute:
      ShellCampaignsCampaignIdEncountersNewRoute,
    ShellCampaignsCampaignIdPartySplatRoute:
      ShellCampaignsCampaignIdPartySplatRoute,
    ShellCampaignsCampaignIdPartySeatIdRoute:
      ShellCampaignsCampaignIdPartySeatIdRoute,
    ShellCampaignsCampaignIdCastIndexRoute:
      ShellCampaignsCampaignIdCastIndexRoute,
    ShellCampaignsCampaignIdEncountersIndexRoute:
      ShellCampaignsCampaignIdEncountersIndexRoute,
    ShellCampaignsCampaignIdPartyIndexRoute:
      ShellCampaignsCampaignIdPartyIndexRoute,
    ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute:
      ShellCampaignsCampaignIdSessionsSessionIdRunsRunIdRoute,
  };

const ShellCampaignsCampaignIdRouteRouteWithChildren =
  ShellCampaignsCampaignIdRouteRoute._addFileChildren(
    ShellCampaignsCampaignIdRouteRouteChildren,
  );

interface ShellWorldsWorldIdRouteRouteChildren {
  ShellWorldsWorldIdChronicleRoute: typeof ShellWorldsWorldIdChronicleRoute;
  ShellWorldsWorldIdIndexRoute: typeof ShellWorldsWorldIdIndexRoute;
}

const ShellWorldsWorldIdRouteRouteChildren: ShellWorldsWorldIdRouteRouteChildren =
  {
    ShellWorldsWorldIdChronicleRoute: ShellWorldsWorldIdChronicleRoute,
    ShellWorldsWorldIdIndexRoute: ShellWorldsWorldIdIndexRoute,
  };

const ShellWorldsWorldIdRouteRouteWithChildren =
  ShellWorldsWorldIdRouteRoute._addFileChildren(
    ShellWorldsWorldIdRouteRouteChildren,
  );

interface ShellRouteChildren {
  ShellSplatRoute: typeof ShellSplatRoute;
  ShellIndexRoute: typeof ShellIndexRoute;
  ShellCampaignsCampaignIdRouteRoute: typeof ShellCampaignsCampaignIdRouteRouteWithChildren;
  ShellWorldsWorldIdRouteRoute: typeof ShellWorldsWorldIdRouteRouteWithChildren;
  ShellCharactersSplatRoute: typeof ShellCharactersSplatRoute;
  ShellCharactersCharacterIdRoute: typeof ShellCharactersCharacterIdRoute;
  ShellCharactersNewRoute: typeof ShellCharactersNewRoute;
  ShellLibraryCompendiumRoute: typeof ShellLibraryCompendiumRoute;
  ShellLibraryEquipmentRoute: typeof ShellLibraryEquipmentRoute;
  ShellLibraryMagicItemsRoute: typeof ShellLibraryMagicItemsRoute;
  ShellLibraryRulesRoute: typeof ShellLibraryRulesRoute;
  ShellLibrarySpellsRoute: typeof ShellLibrarySpellsRoute;
  ShellCampaignsIndexRoute: typeof ShellCampaignsIndexRoute;
  ShellCharactersIndexRoute: typeof ShellCharactersIndexRoute;
  ShellLibraryIndexRoute: typeof ShellLibraryIndexRoute;
  ShellWorldsIndexRoute: typeof ShellWorldsIndexRoute;
  ShellLibraryNpcsSplatRoute: typeof ShellLibraryNpcsSplatRoute;
  ShellLibraryNpcsNpcIdRoute: typeof ShellLibraryNpcsNpcIdRoute;
  ShellLibraryNpcsIndexRoute: typeof ShellLibraryNpcsIndexRoute;
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSplatRoute: ShellSplatRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellCampaignsCampaignIdRouteRoute:
    ShellCampaignsCampaignIdRouteRouteWithChildren,
  ShellWorldsWorldIdRouteRoute: ShellWorldsWorldIdRouteRouteWithChildren,
  ShellCharactersSplatRoute: ShellCharactersSplatRoute,
  ShellCharactersCharacterIdRoute: ShellCharactersCharacterIdRoute,
  ShellCharactersNewRoute: ShellCharactersNewRoute,
  ShellLibraryCompendiumRoute: ShellLibraryCompendiumRoute,
  ShellLibraryEquipmentRoute: ShellLibraryEquipmentRoute,
  ShellLibraryMagicItemsRoute: ShellLibraryMagicItemsRoute,
  ShellLibraryRulesRoute: ShellLibraryRulesRoute,
  ShellLibrarySpellsRoute: ShellLibrarySpellsRoute,
  ShellCampaignsIndexRoute: ShellCampaignsIndexRoute,
  ShellCharactersIndexRoute: ShellCharactersIndexRoute,
  ShellLibraryIndexRoute: ShellLibraryIndexRoute,
  ShellWorldsIndexRoute: ShellWorldsIndexRoute,
  ShellLibraryNpcsSplatRoute: ShellLibraryNpcsSplatRoute,
  ShellLibraryNpcsNpcIdRoute: ShellLibraryNpcsNpcIdRoute,
  ShellLibraryNpcsIndexRoute: ShellLibraryNpcsIndexRoute,
};

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren);

interface StandaloneRouteChildren {
  StandaloneJoinTokenRoute: typeof StandaloneJoinTokenRoute;
}

const StandaloneRouteChildren: StandaloneRouteChildren = {
  StandaloneJoinTokenRoute: StandaloneJoinTokenRoute,
};

const StandaloneRouteWithChildren = StandaloneRoute._addFileChildren(
  StandaloneRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  StandaloneRoute: StandaloneRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
