/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NpcsIndexRouteImport } from './routes/npcs/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as NpcsNpcIdIndexRouteImport } from './routes/npcs/$npcId/index'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns/$campaignId/index'
import { Route as CampaignsCampaignIdConversationsChatIdRouteImport } from './routes/campaigns/$campaignId/conversations/$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsIndexRoute = NpcsIndexRouteImport.update({
  id: '/npcs/',
  path: '/npcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsNpcIdIndexRoute = NpcsNpcIdIndexRouteImport.update({
  id: '/npcs/$npcId/',
  path: '/npcs/$npcId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/campaigns/$campaignId/',
    path: '/campaigns/$campaignId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdConversationsChatIdRoute =
  CampaignsCampaignIdConversationsChatIdRouteImport.update({
    id: '/campaigns/$campaignId/conversations/$chatId',
    path: '/campaigns/$campaignId/conversations/$chatId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/npcs/$npcId/': typeof NpcsNpcIdIndexRoute
  '/campaigns/$campaignId/conversations/$chatId': typeof CampaignsCampaignIdConversationsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/npcs': typeof NpcsIndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/npcs/$npcId': typeof NpcsNpcIdIndexRoute
  '/campaigns/$campaignId/conversations/$chatId': typeof CampaignsCampaignIdConversationsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/npcs/': typeof NpcsIndexRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/npcs/$npcId/': typeof NpcsNpcIdIndexRoute
  '/campaigns/$campaignId/conversations/$chatId': typeof CampaignsCampaignIdConversationsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns/'
    | '/npcs/'
    | '/campaigns/$campaignId/'
    | '/npcs/$npcId/'
    | '/campaigns/$campaignId/conversations/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/npcs'
    | '/campaigns/$campaignId'
    | '/npcs/$npcId'
    | '/campaigns/$campaignId/conversations/$chatId'
  id:
    | '__root__'
    | '/'
    | '/campaigns/'
    | '/npcs/'
    | '/campaigns/$campaignId/'
    | '/npcs/$npcId/'
    | '/campaigns/$campaignId/conversations/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  NpcsIndexRoute: typeof NpcsIndexRoute
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
  NpcsNpcIdIndexRoute: typeof NpcsNpcIdIndexRoute
  CampaignsCampaignIdConversationsChatIdRoute: typeof CampaignsCampaignIdConversationsChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/': {
      id: '/npcs/'
      path: '/npcs'
      fullPath: '/npcs/'
      preLoaderRoute: typeof NpcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs/$npcId/': {
      id: '/npcs/$npcId/'
      path: '/npcs/$npcId'
      fullPath: '/npcs/$npcId/'
      preLoaderRoute: typeof NpcsNpcIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/conversations/$chatId': {
      id: '/campaigns/$campaignId/conversations/$chatId'
      path: '/campaigns/$campaignId/conversations/$chatId'
      fullPath: '/campaigns/$campaignId/conversations/$chatId'
      preLoaderRoute: typeof CampaignsCampaignIdConversationsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  NpcsIndexRoute: NpcsIndexRoute,
  CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
  NpcsNpcIdIndexRoute: NpcsNpcIdIndexRoute,
  CampaignsCampaignIdConversationsChatIdRoute:
    CampaignsCampaignIdConversationsChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
