import { Effect } from "effect";
import { SqlClient } from "effect/sql";

/**
 * An NPC's character-style sheet: a level, a class, a race, armour class, hit
 * points, an optional challenge rating, and the rules half of a character's
 * document (`SheetBody`), so an NPC can one day stand in a fight or a check
 * the way a party member does.
 *
 * ### The NPC carries it; it is not a character
 *
 * A `character` is account-owned and top-level: it is listed in its owner's
 * characters, joins parties through seats, outlives campaign deletes, and a
 * shared seat hands players its whole sheet. An NPC is none of those, so it
 * keeps its own row and gains this one beside it. What is reused is the
 * sheet's document and rules, not the row.
 *
 * ### Its own table, never columns on the NPC
 *
 * `0073_npc_prep.ts`'s reason: a player reads a shared NPC's row and the NPC
 * agent's prompt is compiled from it, so a sheet column on `npc` would be one
 * forgotten select list away from the wire. On its own table no player read
 * touches it; the creator reads it through `CampaignCreatorActor`
 * (`repo/NpcSheets.ts`).
 *
 * ### Keyed by the NPC alone
 *
 * Unlike `npc_prep`, whose key to `npc` names the campaign and so refuses a
 * Library original, this row keys on `npc (id)` only, as
 * `npc_knowledge_fact` does: a sheet is the NPC's own content and travels with
 * it, so a Library original can carry one and a copy into a campaign can take
 * it. Containment is by walking the NPC: every read and write joins `npc`
 * under the NPC's own creator (or Library owner) predicate.
 *
 * ### The columns are a character's, for a character's reasons
 *
 * `level`, `race`, `subrace`, `class_name`, `ac` and `hp_max` under the bounds
 * the character's payloads state (`SheetLevel`, `SheetLabel`, … in
 * `Character.ts`), and `descriptor` generated by `0020`'s expression verbatim,
 * so the half-line reads the same on both. A field earns a column
 * when something reads it without the document: the Cast's line reads the
 * identity, and a fight's seed will read `ac`, `hp_max` and `descriptor`.
 * Everything else is the document. Null is *nobody has said*, as on
 * `character`.
 *
 * `cr` is the one column a character does not have: a rating the DM sets by
 * hand, closed to exactly the ratings the XP table knows (`CHALLENGE_RATINGS`,
 * `EncounterDifficulty.ts`), so a rating written here always has XP. A test
 * pins this check equal to that list (`npc-sheets.test.ts`).
 *
 * No live values yet: nothing can move an NPC's hit points until it can be a
 * combatant, so `hp_current` and `conditions` wait for that migration.
 *
 * **Not campaign content.** No `visibility`: who may read it is its NPC's
 * creator. No player read selects it and search does not index it. It is in
 * `NOT_CONTENT` (`schema.test.ts`). It gained the provenance pair in
 * `0077_npc_sheet_origin.ts`, when the creator's Hob could draft one. Deleting
 * the NPC deletes its sheet; archiving it leaves the sheet alone.
 */
export default Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient;

  yield* sql`
    create table npc_sheet (
      npc_id      uuid primary key references npc (id) on delete cascade,
      level       integer check (level between 1 and 100),
      race        text check (race is null or char_length(race) between 1 and 40),
      subrace     text check (subrace is null or char_length(subrace) between 1 and 40),
      class_name  text check (class_name is null or char_length(class_name) between 1 and 40),
      descriptor  text generated always as (
                    nullif(
                      btrim(
                        coalesce('Level ' || level::text || ' ', '') ||
                        coalesce(subrace || ' ', coalesce(race || ' ', '')) ||
                        coalesce(class_name, '')
                      ),
                    '')
                  ) stored,
      ac          integer check (ac between 0 and 40),
      hp_max      integer check (hp_max between 0 and 10000),
      cr          text
                    constraint npc_sheet_cr_check
                    check (cr in (
                      '0', '1/8', '1/4', '1/2', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                      '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
                      '22', '23', '24', '25', '26', '27', '28', '29', '30'
                    )),
      body        jsonb not null default '{"abilities":[],"traits":[]}'::jsonb,
      version     integer not null default 1,
      created_at  timestamptz not null default now(),
      updated_at  timestamptz not null default now()
    )
  `;
});
