import { Schema } from "effect";
import { AssistantTurnId } from "./Ids.js";

/**
 * Who may see a row.
 *
 * `dm` is the default everywhere — in the column default, in the schema
 * constructor default, and in the read predicate. A table, a payload or an
 * insert that forgets to say anything is DM-only, which is the safe failure.
 * See `AGENTS.md` § "The actor and visibility contract".
 */
export const Visibility = Schema.Literals(["dm", "shared"]);
export type Visibility = typeof Visibility.Type;

/**
 * Where a row's content came from.
 *
 * - `system` — content bundled with the product, written by this project.
 *   Global, immutable; edits produce a copy. **It is not SRD or any other
 *   third-party content** — today it is six fixture creatures
 *   (`apps/server/src/bestiary/systemCreatures.ts`) and twenty-two class and
 *   species rows of names and numbers
 *   (`apps/server/src/ruleset/systemOptions.ts`), and by decision it never
 *   carries third-party prose. See `AGENTS.md` § "The bundle carries no
 *   third-party prose".
 * - `imported` — uploaded by the DM from an external source.
 * - `authored` — written by the DM. The default.
 * - `assistant` — generated by the assistant *and explicitly accepted* by the
 *   DM, in which case `assistantTurnId` records the conversation turn.
 *
 * **`assistant` is written in exactly one place** — `repo/Proposals.ts`, when a
 * human accepts something Hob proposed. There is no payload field for it, so a
 * client cannot claim it. The columns were here from the first migration and
 * inert for nine, because retrofitting provenance onto a table that already
 * mixes authored and generated rows means guessing which is which.
 */
export const Origin = Schema.Literals(["system", "imported", "authored", "assistant"]);
export type Origin = typeof Origin.Type;

/**
 * The provenance pair carried by every content-bearing row. Enforced in the
 * database too: `origin = 'assistant'` exactly when `assistant_turn_id` is set.
 */
export const provenanceFields = {
  origin: Origin,
  assistantTurnId: Schema.NullOr(AssistantTurnId),
} as const;
